

// -------------------------------------------------------------
// 
// File Name: hdlsrc/matrix_multiplication/MATLAB_Function.v
// Created: 2024-12-18 11:07:15
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: matrix_multiplication/MATLAB Function
// Hierarchy Level: 1
// Model version: 1.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (a,
           b,
           y);


  input   signed [7:0] a;  // int8
  input   signed [7:0] b;  // int8
  output  signed [7:0] y;  // int8


  wire signed [15:0] mul_temp;  // sfix16


  assign mul_temp = a * b;
  assign y = ((mul_temp[15] == 1'b0) && (mul_temp[14:7] != 8'b00000000) ? 8'sb01111111 :
              ((mul_temp[15] == 1'b1) && (mul_temp[14:7] != 8'b11111111) ? 8'sb10000000 :
              $signed(mul_temp[7:0])));

endmodule  // MATLAB_Function

has popup